# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FitbitBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-sdk4:
    name: Build SDK4
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Setup node
      uses: actions/setup-node@v1

    - name: Select SDK 4
      run: cp package.sdk4.json package.json

    - name: Checkout Fitbit SDK
      run: npm add --also=dev @fitbit/sdk

    - name: Checkout Fitbit SDK-CLI
      run: npm add --also=dev @fitbit/sdk-cli

    - name: Run Build
      run: npx fitbit-build --if-present

    - name: Copy App
      run: cp build/app.fba build/app.sdk4.fba

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        path: build/app.sdk4.fba
        if-no-files-found: error

  build-sdk6:
    name: Build SDK6
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Setup node
      uses: actions/setup-node@v1

    - name: Select SDK 6
      run: cp package.sdk6.json package.json

    - name: Checkout Fitbit SDK
      run: npm add --also=dev @fitbit/sdk

    - name: Checkout Fitbit SDK-CLI
      run: npm add --also=dev @fitbit/sdk-cli

    - name: Run Build
      run: npx fitbit-build --if-present

    - name: Copy App
      run: cp build/app.fba build/app.sdk6.fba

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        path: build/app.sdk6.fba
        if-no-files-found: error
